// OpenWeatherMap Weather Condition Codes
export const OpenWeatherConditionCode = {
    // Thunderstorm
    THUNDERSTORM_LIGHT_RAIN: 200,
    THUNDERSTORM_RAIN: 201,
    THUNDERSTORM_HEAVY_RAIN: 202,
    THUNDERSTORM_LIGHT_DRIZZLE: 230,
    THUNDERSTORM_DRIZZLE: 231,
    THUNDERSTORM_HEAVY_DRIZZLE: 232,
    THUNDERSTORM: 210,
    THUNDERSTORM_HEAVY: 211,
    THUNDERSTORM_VIOLENT: 212,
    THUNDERSTORM_RAGGED: 221,
    // Drizzle
    DRIZZLE_LIGHT: 300,
    DRIZZLE: 301,
    DRIZZLE_HEAVY: 302,
    DRIZZLE_LIGHT_RAIN: 310,
    DRIZZLE_RAIN: 311,
    DRIZZLE_HEAVY_RAIN: 312,
    DRIZZLE_SHOWER: 313,
    DRIZZLE_SHOWER_RAIN: 314,
    DRIZZLE_SHOWER_DRIZZLE: 321,
    // Rain
    RAIN_LIGHT: 500,
    RAIN_MODERATE: 501,
    RAIN_HEAVY: 502,
    RAIN_VERY_HEAVY: 503,
    RAIN_EXTREME: 504,
    RAIN_FREEZING: 511,
    RAIN_SHOWER_LIGHT: 520,
    RAIN_SHOWER: 521,
    RAIN_SHOWER_HEAVY: 522,
    RAIN_SHOWER_RAGGED: 531,
    // Snow
    SNOW_LIGHT: 600,
    SNOW: 601,
    SNOW_HEAVY: 602,
    SNOW_SLEET: 611,
    SNOW_SHOWER_SLEET: 612,
    SNOW_LIGHT_SLEET: 613,
    SNOW_LIGHT_SHOWER: 615,
    SNOW_RAIN: 616,
    SNOW_SHOWER_LIGHT: 620,
    SNOW_SHOWER: 621,
    SNOW_SHOWER_HEAVY: 622,

    // Atmosphere
    MIST: 701,
    SMOKE: 711,
    HAZE: 721,
    DUST_WHIRLS: 731,
    FOG: 741,
    SAND: 751,
    DUST: 761,
    ASH: 762,
    SQUALL: 771,
    TORNADO: 781,
    // Clear
    CLEAR: 800,
    // Clouds
    CLOUDS_FEW: 801,
    CLOUDS_SCATTERED: 802,
    CLOUDS_BROKEN: 803,
    CLOUDS_OVERCAST: 804,
} as const

export type OpenWeatherConditionCode =
    typeof OpenWeatherConditionCode[keyof typeof OpenWeatherConditionCode]

export const alertConditions: OpenWeatherConditionCode[] = [
    // Thunderstorm
    OpenWeatherConditionCode.THUNDERSTORM_LIGHT_RAIN,
    OpenWeatherConditionCode.THUNDERSTORM_RAIN,
    OpenWeatherConditionCode.THUNDERSTORM_HEAVY_RAIN,
    OpenWeatherConditionCode.THUNDERSTORM_LIGHT_DRIZZLE,
    OpenWeatherConditionCode.THUNDERSTORM_DRIZZLE,
    OpenWeatherConditionCode.THUNDERSTORM_HEAVY_DRIZZLE,
    OpenWeatherConditionCode.THUNDERSTORM,
    OpenWeatherConditionCode.THUNDERSTORM_HEAVY,
    OpenWeatherConditionCode.THUNDERSTORM_VIOLENT,
    OpenWeatherConditionCode.THUNDERSTORM_RAGGED,
    // Drizzle
    OpenWeatherConditionCode.DRIZZLE_LIGHT,
    OpenWeatherConditionCode.DRIZZLE,
    OpenWeatherConditionCode.DRIZZLE_HEAVY,
    OpenWeatherConditionCode.DRIZZLE_LIGHT_RAIN,
    OpenWeatherConditionCode.DRIZZLE_RAIN,
    OpenWeatherConditionCode.DRIZZLE_HEAVY_RAIN,
    OpenWeatherConditionCode.DRIZZLE_SHOWER,
    OpenWeatherConditionCode.DRIZZLE_SHOWER_RAIN,
    OpenWeatherConditionCode.DRIZZLE_SHOWER_DRIZZLE,
    // Rain
    OpenWeatherConditionCode.RAIN_LIGHT,
    OpenWeatherConditionCode.RAIN_MODERATE,
    OpenWeatherConditionCode.RAIN_HEAVY,
    OpenWeatherConditionCode.RAIN_VERY_HEAVY,
    OpenWeatherConditionCode.RAIN_EXTREME,
    OpenWeatherConditionCode.RAIN_FREEZING,
    OpenWeatherConditionCode.RAIN_SHOWER_LIGHT,
    OpenWeatherConditionCode.RAIN_SHOWER,
    OpenWeatherConditionCode.RAIN_SHOWER_HEAVY,
    OpenWeatherConditionCode.RAIN_SHOWER_RAGGED,
    // Snow
    OpenWeatherConditionCode.SNOW_LIGHT,
    OpenWeatherConditionCode.SNOW,
    OpenWeatherConditionCode.SNOW_HEAVY,
    OpenWeatherConditionCode.SNOW_SLEET,
    OpenWeatherConditionCode.SNOW_SHOWER_SLEET,
    OpenWeatherConditionCode.SNOW_LIGHT_SLEET,
    OpenWeatherConditionCode.SNOW_LIGHT_SHOWER,
    OpenWeatherConditionCode.SNOW_RAIN,
    OpenWeatherConditionCode.SNOW_SHOWER_LIGHT,
    OpenWeatherConditionCode.SNOW_SHOWER,
    OpenWeatherConditionCode.SNOW_SHOWER_HEAVY,
    // Atmosphere
    OpenWeatherConditionCode.MIST,
    OpenWeatherConditionCode.SMOKE,
    OpenWeatherConditionCode.HAZE,
    OpenWeatherConditionCode.DUST_WHIRLS,
    OpenWeatherConditionCode.FOG,
    OpenWeatherConditionCode.SAND,
    OpenWeatherConditionCode.DUST,
    OpenWeatherConditionCode.ASH,
    OpenWeatherConditionCode.SQUALL,
    OpenWeatherConditionCode.TORNADO,
    // Clear / clouds
    OpenWeatherConditionCode.CLEAR,
    OpenWeatherConditionCode.CLOUDS_FEW,
    OpenWeatherConditionCode.CLOUDS_SCATTERED,
    OpenWeatherConditionCode.CLOUDS_BROKEN,
    OpenWeatherConditionCode.CLOUDS_OVERCAST,
]
